/*
 * generated by Xtext 2.22.0
 */
package uclid.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import uclid.xtext.services.UclidGrammarAccess;

@SuppressWarnings("all")
public class UclidSyntacticSequencer extends AbstractSyntacticSequencer {

	protected UclidGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AssignmentRule_CommaKeyword_1_1_0_q;
	protected AbstractElementAlias match_AxiomDeclRule_AssumeKeyword_0_0_1_or_AxiomKeyword_0_0_0;
	protected AbstractElementAlias match_AxiomDeclRule_AssumeKeyword_1_0_1_or_AxiomKeyword_1_0_0;
	protected AbstractElementAlias match_CmdRule___IDTerminalRuleCall_1_0_FullStopKeyword_1_1__q;
	protected AbstractElementAlias match_CmdRule___LeftParenthesisKeyword_4_0_RightParenthesisKeyword_4_2__q;
	protected AbstractElementAlias match_ConstsDeclRule___EqualsSignKeyword_5_0_INTTerminalRuleCall_5_1__q;
	protected AbstractElementAlias match_E12Rule___LeftParenthesisKeyword_1_0_RightParenthesisKeyword_1_2__q;
	protected AbstractElementAlias match_InputsDeclRule_OutputsDeclRule_SharedVarsDeclRule_InputKeyword_0_or_OutputKeyword_0_or_SharedvarKeyword_0;
	protected AbstractElementAlias match_InvariantClauseRule_InvariantKeyword_0_1_or_PropertyKeyword_0_0;
	protected AbstractElementAlias match_InvariantClauseRule___LeftSquareBracketKeyword_1_0_LTLKeyword_1_1_RightSquareBracketKeyword_1_2__q;
	protected AbstractElementAlias match_Lhs_ApostropheKeyword_3_q;
	protected AbstractElementAlias match_StatementRule_SemicolonKeyword_10_1_q;
	protected AbstractElementAlias match_StatementRule_SemicolonKeyword_11_1_q;
	protected AbstractElementAlias match_StatementRule_SemicolonKeyword_7_1_q;
	protected AbstractElementAlias match_StatementRule_SemicolonKeyword_8_1_q;
	protected AbstractElementAlias match_StatementRule_SemicolonKeyword_9_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (UclidGrammarAccess) access;
		match_AssignmentRule_CommaKeyword_1_1_0_q = new TokenAlias(false, true, grammarAccess.getAssignmentRuleAccess().getCommaKeyword_1_1_0());
		match_AxiomDeclRule_AssumeKeyword_0_0_1_or_AxiomKeyword_0_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAxiomDeclRuleAccess().getAssumeKeyword_0_0_1()), new TokenAlias(false, false, grammarAccess.getAxiomDeclRuleAccess().getAxiomKeyword_0_0_0()));
		match_AxiomDeclRule_AssumeKeyword_1_0_1_or_AxiomKeyword_1_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAxiomDeclRuleAccess().getAssumeKeyword_1_0_1()), new TokenAlias(false, false, grammarAccess.getAxiomDeclRuleAccess().getAxiomKeyword_1_0_0()));
		match_CmdRule___IDTerminalRuleCall_1_0_FullStopKeyword_1_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCmdRuleAccess().getIDTerminalRuleCall_1_0()), new TokenAlias(false, false, grammarAccess.getCmdRuleAccess().getFullStopKeyword_1_1()));
		match_CmdRule___LeftParenthesisKeyword_4_0_RightParenthesisKeyword_4_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCmdRuleAccess().getLeftParenthesisKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getCmdRuleAccess().getRightParenthesisKeyword_4_2()));
		match_ConstsDeclRule___EqualsSignKeyword_5_0_INTTerminalRuleCall_5_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getConstsDeclRuleAccess().getEqualsSignKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getConstsDeclRuleAccess().getINTTerminalRuleCall_5_1()));
		match_E12Rule___LeftParenthesisKeyword_1_0_RightParenthesisKeyword_1_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getE12RuleAccess().getLeftParenthesisKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getE12RuleAccess().getRightParenthesisKeyword_1_2()));
		match_InputsDeclRule_OutputsDeclRule_SharedVarsDeclRule_InputKeyword_0_or_OutputKeyword_0_or_SharedvarKeyword_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getInputsDeclRuleAccess().getInputKeyword_0()), new TokenAlias(false, false, grammarAccess.getOutputsDeclRuleAccess().getOutputKeyword_0()), new TokenAlias(false, false, grammarAccess.getSharedVarsDeclRuleAccess().getSharedvarKeyword_0()));
		match_InvariantClauseRule_InvariantKeyword_0_1_or_PropertyKeyword_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getInvariantClauseRuleAccess().getInvariantKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getInvariantClauseRuleAccess().getPropertyKeyword_0_0()));
		match_InvariantClauseRule___LeftSquareBracketKeyword_1_0_LTLKeyword_1_1_RightSquareBracketKeyword_1_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInvariantClauseRuleAccess().getLeftSquareBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getInvariantClauseRuleAccess().getLTLKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getInvariantClauseRuleAccess().getRightSquareBracketKeyword_1_2()));
		match_Lhs_ApostropheKeyword_3_q = new TokenAlias(false, true, grammarAccess.getLhsAccess().getApostropheKeyword_3());
		match_StatementRule_SemicolonKeyword_10_1_q = new TokenAlias(false, true, grammarAccess.getStatementRuleAccess().getSemicolonKeyword_10_1());
		match_StatementRule_SemicolonKeyword_11_1_q = new TokenAlias(false, true, grammarAccess.getStatementRuleAccess().getSemicolonKeyword_11_1());
		match_StatementRule_SemicolonKeyword_7_1_q = new TokenAlias(false, true, grammarAccess.getStatementRuleAccess().getSemicolonKeyword_7_1());
		match_StatementRule_SemicolonKeyword_8_1_q = new TokenAlias(false, true, grammarAccess.getStatementRuleAccess().getSemicolonKeyword_8_1());
		match_StatementRule_SemicolonKeyword_9_1_q = new TokenAlias(false, true, grammarAccess.getStatementRuleAccess().getSemicolonKeyword_9_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getINTRule())
			return getINTToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * terminal INT returns ecore::EInt: ('0'..'9')+;
	 */
	protected String getINTToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AssignmentRule_CommaKeyword_1_1_0_q.equals(syntax))
				emit_AssignmentRule_CommaKeyword_1_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AxiomDeclRule_AssumeKeyword_0_0_1_or_AxiomKeyword_0_0_0.equals(syntax))
				emit_AxiomDeclRule_AssumeKeyword_0_0_1_or_AxiomKeyword_0_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AxiomDeclRule_AssumeKeyword_1_0_1_or_AxiomKeyword_1_0_0.equals(syntax))
				emit_AxiomDeclRule_AssumeKeyword_1_0_1_or_AxiomKeyword_1_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CmdRule___IDTerminalRuleCall_1_0_FullStopKeyword_1_1__q.equals(syntax))
				emit_CmdRule___IDTerminalRuleCall_1_0_FullStopKeyword_1_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CmdRule___LeftParenthesisKeyword_4_0_RightParenthesisKeyword_4_2__q.equals(syntax))
				emit_CmdRule___LeftParenthesisKeyword_4_0_RightParenthesisKeyword_4_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ConstsDeclRule___EqualsSignKeyword_5_0_INTTerminalRuleCall_5_1__q.equals(syntax))
				emit_ConstsDeclRule___EqualsSignKeyword_5_0_INTTerminalRuleCall_5_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_E12Rule___LeftParenthesisKeyword_1_0_RightParenthesisKeyword_1_2__q.equals(syntax))
				emit_E12Rule___LeftParenthesisKeyword_1_0_RightParenthesisKeyword_1_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InputsDeclRule_OutputsDeclRule_SharedVarsDeclRule_InputKeyword_0_or_OutputKeyword_0_or_SharedvarKeyword_0.equals(syntax))
				emit_InputsDeclRule_OutputsDeclRule_SharedVarsDeclRule_InputKeyword_0_or_OutputKeyword_0_or_SharedvarKeyword_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InvariantClauseRule_InvariantKeyword_0_1_or_PropertyKeyword_0_0.equals(syntax))
				emit_InvariantClauseRule_InvariantKeyword_0_1_or_PropertyKeyword_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InvariantClauseRule___LeftSquareBracketKeyword_1_0_LTLKeyword_1_1_RightSquareBracketKeyword_1_2__q.equals(syntax))
				emit_InvariantClauseRule___LeftSquareBracketKeyword_1_0_LTLKeyword_1_1_RightSquareBracketKeyword_1_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Lhs_ApostropheKeyword_3_q.equals(syntax))
				emit_Lhs_ApostropheKeyword_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatementRule_SemicolonKeyword_10_1_q.equals(syntax))
				emit_StatementRule_SemicolonKeyword_10_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatementRule_SemicolonKeyword_11_1_q.equals(syntax))
				emit_StatementRule_SemicolonKeyword_11_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatementRule_SemicolonKeyword_7_1_q.equals(syntax))
				emit_StatementRule_SemicolonKeyword_7_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatementRule_SemicolonKeyword_8_1_q.equals(syntax))
				emit_StatementRule_SemicolonKeyword_8_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatementRule_SemicolonKeyword_9_1_q.equals(syntax))
				emit_StatementRule_SemicolonKeyword_9_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     lhs+=Lhs (ambiguity) '=' exprs+=ExprRule
	 */
	protected void emit_AssignmentRule_CommaKeyword_1_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'axiom' | 'assume'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) n=ID
	 */
	protected void emit_AxiomDeclRule_AssumeKeyword_0_0_1_or_AxiomKeyword_0_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'axiom' | 'assume'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) h=ExprRule
	 */
	protected void emit_AxiomDeclRule_AssumeKeyword_1_0_1_or_AxiomKeyword_1_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (ID '.')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) c=CmdNameRule
	 *     lhs=VarDecl '=' (ambiguity) c=CmdNameRule
	 */
	protected void emit_CmdRule___IDTerminalRuleCall_1_0_FullStopKeyword_1_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     c=CmdNameRule (ambiguity) ';' (rule end)
	 *     lid=IdListRule ']' (ambiguity) ';' (rule end)
	 */
	protected void emit_CmdRule___LeftParenthesisKeyword_4_0_RightParenthesisKeyword_4_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('=' INT)?
	 *
	 * This ambiguous syntax occurs at:
	 *     t=TypeRule (ambiguity) ';' (rule end)
	 */
	protected void emit_ConstsDeclRule___EqualsSignKeyword_5_0_INTTerminalRuleCall_5_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     j=E13Rule (ambiguity) '[' l+=ExprListRule
	 *     j=E13Rule (ambiguity) (rule end)
	 */
	protected void emit_E12Rule___LeftParenthesisKeyword_1_0_RightParenthesisKeyword_1_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'input' | 'output' | 'sharedvar'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name+=ID
	 */
	protected void emit_InputsDeclRule_OutputsDeclRule_SharedVarsDeclRule_InputKeyword_0_or_OutputKeyword_0_or_SharedvarKeyword_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'property' | 'invariant'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ('[' 'LTL' ']')? e=ExprRule
	 */
	protected void emit_InvariantClauseRule_InvariantKeyword_0_1_or_PropertyKeyword_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('[' 'LTL' ']')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) ('property' | 'invariant') (ambiguity) e=ExprRule
	 */
	protected void emit_InvariantClauseRule___LeftSquareBracketKeyword_1_0_LTLKeyword_1_1_RightSquareBracketKeyword_1_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '''?
	 *
	 * This ambiguous syntax occurs at:
	 *     index+=ExprRule ']' (ambiguity) (rule end)
	 *     target=LhsVarRef (ambiguity) (rule end)
	 */
	protected void emit_Lhs_ApostropheKeyword_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     s=WhileLoopRule (ambiguity) (rule end)
	 */
	protected void emit_StatementRule_SemicolonKeyword_10_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     s=BlkStmtRule (ambiguity) (rule end)
	 */
	protected void emit_StatementRule_SemicolonKeyword_11_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     s=IfStmtRule (ambiguity) (rule end)
	 */
	protected void emit_StatementRule_SemicolonKeyword_7_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     s=CaseStmtRule (ambiguity) (rule end)
	 */
	protected void emit_StatementRule_SemicolonKeyword_8_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     s=ForLoopRule (ambiguity) (rule end)
	 */
	protected void emit_StatementRule_SemicolonKeyword_9_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
