/*
 * generated by Xtext 2.22.0
 */
package uclid.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UclidRuntimeModule extends AbstractUclidRuntimeModule {
}
