/*
 * generated by Xtext 2.22.0
 */
package uclid.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UclidStandaloneSetup extends UclidStandaloneSetupGenerated {

	def static void doSetup() {
		new UclidStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
