/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uclid.xtext.uclid.CompoundStatement;
import uclid.xtext.uclid.Statement;
import uclid.xtext.uclid.UclidPackage;
import uclid.xtext.uclid.VarsDeclRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Compound Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.impl.CompoundStatementImpl#getDec <em>Dec</em>}</li>
 *   <li>{@link uclid.xtext.uclid.impl.CompoundStatementImpl#getStmt <em>Stmt</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompoundStatementImpl extends MinimalEObjectImpl.Container implements CompoundStatement
{
  /**
   * The cached value of the '{@link #getDec() <em>Dec</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDec()
   * @generated
   * @ordered
   */
  protected EList<VarsDeclRule> dec;

  /**
   * The cached value of the '{@link #getStmt() <em>Stmt</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStmt()
   * @generated
   * @ordered
   */
  protected EList<Statement> stmt;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompoundStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UclidPackage.Literals.COMPOUND_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<VarsDeclRule> getDec()
  {
    if (dec == null)
    {
      dec = new EObjectContainmentEList<VarsDeclRule>(VarsDeclRule.class, this, UclidPackage.COMPOUND_STATEMENT__DEC);
    }
    return dec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Statement> getStmt()
  {
    if (stmt == null)
    {
      stmt = new EObjectContainmentEList<Statement>(Statement.class, this, UclidPackage.COMPOUND_STATEMENT__STMT);
    }
    return stmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UclidPackage.COMPOUND_STATEMENT__DEC:
        return ((InternalEList<?>)getDec()).basicRemove(otherEnd, msgs);
      case UclidPackage.COMPOUND_STATEMENT__STMT:
        return ((InternalEList<?>)getStmt()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UclidPackage.COMPOUND_STATEMENT__DEC:
        return getDec();
      case UclidPackage.COMPOUND_STATEMENT__STMT:
        return getStmt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UclidPackage.COMPOUND_STATEMENT__DEC:
        getDec().clear();
        getDec().addAll((Collection<? extends VarsDeclRule>)newValue);
        return;
      case UclidPackage.COMPOUND_STATEMENT__STMT:
        getStmt().clear();
        getStmt().addAll((Collection<? extends Statement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UclidPackage.COMPOUND_STATEMENT__DEC:
        getDec().clear();
        return;
      case UclidPackage.COMPOUND_STATEMENT__STMT:
        getStmt().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UclidPackage.COMPOUND_STATEMENT__DEC:
        return dec != null && !dec.isEmpty();
      case UclidPackage.COMPOUND_STATEMENT__STMT:
        return stmt != null && !stmt.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CompoundStatementImpl
