/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid.impl;

import org.eclipse.emf.ecore.EClass;

import uclid.xtext.uclid.ExprRule;
import uclid.xtext.uclid.UclidPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExprRuleImpl extends ParenthesisExprImpl implements ExprRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UclidPackage.Literals.EXPR_RULE;
  }

} //ExprRuleImpl
