/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid.impl;

import org.eclipse.emf.ecore.EClass;

import uclid.xtext.uclid.OutputsDeclRule;
import uclid.xtext.uclid.UclidPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Outputs Decl Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OutputsDeclRuleImpl extends DeclRuleImpl implements OutputsDeclRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutputsDeclRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UclidPackage.Literals.OUTPUTS_DECL_RULE;
  }

} //OutputsDeclRuleImpl
