/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid.impl;

import org.eclipse.emf.ecore.EClass;

import uclid.xtext.uclid.SharedVarsDeclRule;
import uclid.xtext.uclid.UclidPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Shared Vars Decl Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SharedVarsDeclRuleImpl extends DeclRuleImpl implements SharedVarsDeclRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SharedVarsDeclRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UclidPackage.Literals.SHARED_VARS_DECL_RULE;
  }

} //SharedVarsDeclRuleImpl
