/*
 * generated by Xtext 2.24.0
 */
package uclid.xtext.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class UclidNewProjectWizard extends XtextNewProjectWizard {

	private UclidWizardNewProjectCreationPage mainPage;

	@Inject
	public UclidNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New Uclid Project");
	}

	protected UclidWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("Uclid Project");
		mainPage.setDescription("Create a new Uclid project.");
		addPage(mainPage);
	}

	protected UclidWizardNewProjectCreationPage createMainPage(String pageName) {
		return new UclidWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		UclidProjectInfo projectInfo = new UclidProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
