/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.serializer;

import uclid.xtext.serializer.AbstractUclidSyntacticSequencer;

@SuppressWarnings("all")
public class UclidSyntacticSequencer extends AbstractUclidSyntacticSequencer {
}
