/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uclid.xtext.ui.AbstractUclidUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UclidUiModule extends AbstractUclidUiModule {
  public UclidUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
