/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.validation;

import uclid.xtext.validation.AbstractUclidValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UclidValidator extends AbstractUclidValidator {
}
