/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext;

import uclid.xtext.UclidStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UclidStandaloneSetup extends UclidStandaloneSetupGenerated {
  public static void doSetup() {
    new UclidStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
