/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext;

import uclid.xtext.AbstractUclidRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UclidRuntimeModule extends AbstractUclidRuntimeModule {
}
