/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arg Map List Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.ArgMapListRule#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getArgMapListRule()
 * @model
 * @generated
 */
public interface ArgMapListRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Arg</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.ArgMapRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getArgMapListRule_Arg()
   * @model containment="true"
   * @generated
   */
  EList<ArgMapRule> getArg();

} // ArgMapListRule
