/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Type Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.ArrayTypeRule#getB <em>B</em>}</li>
 *   <li>{@link uclid.xtext.uclid.ArrayTypeRule#getBase <em>Base</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getArrayTypeRule()
 * @model
 * @generated
 */
public interface ArrayTypeRule extends Type
{
  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getArrayTypeRule_B()
   * @model containment="true"
   * @generated
   */
  EList<Type> getB();

  /**
   * Returns the value of the '<em><b>Base</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getArrayTypeRule_Base()
   * @model containment="true"
   * @generated
   */
  EList<Type> getBase();

} // ArrayTypeRule
