/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Axiom Decl Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.AxiomDeclRule#getN <em>N</em>}</li>
 *   <li>{@link uclid.xtext.uclid.AxiomDeclRule#getE <em>E</em>}</li>
 *   <li>{@link uclid.xtext.uclid.AxiomDeclRule#getH <em>H</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getAxiomDeclRule()
 * @model
 * @generated
 */
public interface AxiomDeclRule extends DeclRule
{
  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(String)
   * @see uclid.xtext.uclid.UclidPackage#getAxiomDeclRule_N()
   * @model
   * @generated
   */
  String getN();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.AxiomDeclRule#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(String value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(ExprRule)
   * @see uclid.xtext.uclid.UclidPackage#getAxiomDeclRule_E()
   * @model containment="true"
   * @generated
   */
  ExprRule getE();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.AxiomDeclRule#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(ExprRule value);

  /**
   * Returns the value of the '<em><b>H</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H</em>' containment reference.
   * @see #setH(ExprRule)
   * @see uclid.xtext.uclid.UclidPackage#getAxiomDeclRule_H()
   * @model containment="true"
   * @generated
   */
  ExprRule getH();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.AxiomDeclRule#getH <em>H</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H</em>' containment reference.
   * @see #getH()
   * @generated
   */
  void setH(ExprRule value);

} // AxiomDeclRule
