/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cmd Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.CmdRule#getLhs <em>Lhs</em>}</li>
 *   <li>{@link uclid.xtext.uclid.CmdRule#getC <em>C</em>}</li>
 *   <li>{@link uclid.xtext.uclid.CmdRule#getLid <em>Lid</em>}</li>
 *   <li>{@link uclid.xtext.uclid.CmdRule#getLex <em>Lex</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getCmdRule()
 * @model
 * @generated
 */
public interface CmdRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' containment reference.
   * @see #setLhs(VarDecl)
   * @see uclid.xtext.uclid.UclidPackage#getCmdRule_Lhs()
   * @model containment="true"
   * @generated
   */
  VarDecl getLhs();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.CmdRule#getLhs <em>Lhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' containment reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(VarDecl value);

  /**
   * Returns the value of the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' attribute.
   * @see #setC(String)
   * @see uclid.xtext.uclid.UclidPackage#getCmdRule_C()
   * @model
   * @generated
   */
  String getC();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.CmdRule#getC <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' attribute.
   * @see #getC()
   * @generated
   */
  void setC(String value);

  /**
   * Returns the value of the '<em><b>Lid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lid</em>' containment reference.
   * @see #setLid(IdListRule)
   * @see uclid.xtext.uclid.UclidPackage#getCmdRule_Lid()
   * @model containment="true"
   * @generated
   */
  IdListRule getLid();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.CmdRule#getLid <em>Lid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lid</em>' containment reference.
   * @see #getLid()
   * @generated
   */
  void setLid(IdListRule value);

  /**
   * Returns the value of the '<em><b>Lex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lex</em>' containment reference.
   * @see #setLex(ExprListRule)
   * @see uclid.xtext.uclid.UclidPackage#getCmdRule_Lex()
   * @model containment="true"
   * @generated
   */
  ExprListRule getLex();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.CmdRule#getLex <em>Lex</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lex</em>' containment reference.
   * @see #getLex()
   * @generated
   */
  void setLex(ExprListRule value);

} // CmdRule
