/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compound Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.CompoundStatement#getDec <em>Dec</em>}</li>
 *   <li>{@link uclid.xtext.uclid.CompoundStatement#getStmt <em>Stmt</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getCompoundStatement()
 * @model
 * @generated
 */
public interface CompoundStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Dec</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.VarsDeclRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getCompoundStatement_Dec()
   * @model containment="true"
   * @generated
   */
  EList<VarsDeclRule> getDec();

  /**
   * Returns the value of the '<em><b>Stmt</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getCompoundStatement_Stmt()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStmt();

} // CompoundStatement
