/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.ConstRule#getV <em>V</em>}</li>
 *   <li>{@link uclid.xtext.uclid.ConstRule#getD <em>D</em>}</li>
 *   <li>{@link uclid.xtext.uclid.ConstRule#getW <em>W</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getConstRule()
 * @model
 * @generated
 */
public interface ConstRule extends E13Rule
{
  /**
   * Returns the value of the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' attribute.
   * @see #setV(String)
   * @see uclid.xtext.uclid.UclidPackage#getConstRule_V()
   * @model
   * @generated
   */
  String getV();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ConstRule#getV <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' attribute.
   * @see #getV()
   * @generated
   */
  void setV(String value);

  /**
   * Returns the value of the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' attribute.
   * @see #setD(int)
   * @see uclid.xtext.uclid.UclidPackage#getConstRule_D()
   * @model
   * @generated
   */
  int getD();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ConstRule#getD <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' attribute.
   * @see #getD()
   * @generated
   */
  void setD(int value);

  /**
   * Returns the value of the '<em><b>W</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' attribute.
   * @see #setW(String)
   * @see uclid.xtext.uclid.UclidPackage#getConstRule_W()
   * @model
   * @generated
   */
  String getW();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ConstRule#getW <em>W</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>W</em>' attribute.
   * @see #getW()
   * @generated
   */
  void setW(String value);

} // ConstRule
