/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control Block Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.ControlBlockRule#getCmd <em>Cmd</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getControlBlockRule()
 * @model
 * @generated
 */
public interface ControlBlockRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Cmd</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.CmdRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getControlBlockRule_Cmd()
   * @model containment="true"
   * @generated
   */
  EList<CmdRule> getCmd();

} // ControlBlockRule
