/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decl Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getDeclRule()
 * @model
 * @generated
 */
public interface DeclRule extends EObject
{
} // DeclRule
