/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default Case Block Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.DefaultCaseBlockRule#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getDefaultCaseBlockRule()
 * @model
 * @generated
 */
public interface DefaultCaseBlockRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(CompoundStatement)
   * @see uclid.xtext.uclid.UclidPackage#getDefaultCaseBlockRule_Body()
   * @model containment="true"
   * @generated
   */
  CompoundStatement getBody();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.DefaultCaseBlockRule#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(CompoundStatement value);

} // DefaultCaseBlockRule
