/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>E10 Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.E10Rule#getOp <em>Op</em>}</li>
 *   <li>{@link uclid.xtext.uclid.E10Rule#getE <em>E</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getE10Rule()
 * @model
 * @generated
 */
public interface E10Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see uclid.xtext.uclid.UclidPackage#getE10Rule_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.E10Rule#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(E11Rule)
   * @see uclid.xtext.uclid.UclidPackage#getE10Rule_E()
   * @model containment="true"
   * @generated
   */
  E11Rule getE();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.E10Rule#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(E11Rule value);

} // E10Rule
