/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>E2 Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.E2Rule#getZ <em>Z</em>}</li>
 *   <li>{@link uclid.xtext.uclid.E2Rule#getQ <em>Q</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getE2Rule()
 * @model
 * @generated
 */
public interface E2Rule extends E1Rule
{
  /**
   * Returns the value of the '<em><b>Z</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.E3Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getE2Rule_Z()
   * @model containment="true"
   * @generated
   */
  EList<E3Rule> getZ();

  /**
   * Returns the value of the '<em><b>Q</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getE2Rule_Q()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getQ();

} // E2Rule
