/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Loop Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.ForLoopRule#getIterator <em>Iterator</em>}</li>
 *   <li>{@link uclid.xtext.uclid.ForLoopRule#getLb <em>Lb</em>}</li>
 *   <li>{@link uclid.xtext.uclid.ForLoopRule#getUb <em>Ub</em>}</li>
 *   <li>{@link uclid.xtext.uclid.ForLoopRule#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getForLoopRule()
 * @model
 * @generated
 */
public interface ForLoopRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Iterator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterator</em>' containment reference.
   * @see #setIterator(VarDecl)
   * @see uclid.xtext.uclid.UclidPackage#getForLoopRule_Iterator()
   * @model containment="true"
   * @generated
   */
  VarDecl getIterator();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ForLoopRule#getIterator <em>Iterator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iterator</em>' containment reference.
   * @see #getIterator()
   * @generated
   */
  void setIterator(VarDecl value);

  /**
   * Returns the value of the '<em><b>Lb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lb</em>' containment reference.
   * @see #setLb(ConstRule)
   * @see uclid.xtext.uclid.UclidPackage#getForLoopRule_Lb()
   * @model containment="true"
   * @generated
   */
  ConstRule getLb();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ForLoopRule#getLb <em>Lb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lb</em>' containment reference.
   * @see #getLb()
   * @generated
   */
  void setLb(ConstRule value);

  /**
   * Returns the value of the '<em><b>Ub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ub</em>' containment reference.
   * @see #setUb(ConstRule)
   * @see uclid.xtext.uclid.UclidPackage#getForLoopRule_Ub()
   * @model containment="true"
   * @generated
   */
  ConstRule getUb();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ForLoopRule#getUb <em>Ub</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ub</em>' containment reference.
   * @see #getUb()
   * @generated
   */
  void setUb(ConstRule value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(CompoundStatement)
   * @see uclid.xtext.uclid.UclidPackage#getForLoopRule_Body()
   * @model containment="true"
   * @generated
   */
  CompoundStatement getBody();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.ForLoopRule#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(CompoundStatement value);

} // ForLoopRule
