/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inputs Decl Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getInputsDeclRule()
 * @model
 * @generated
 */
public interface InputsDeclRule extends DeclRule
{
} // InputsDeclRule
