/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getInputDecl()
 * @model
 * @generated
 */
public interface InputDecl extends TypedObjectDecl
{
} // InputDecl
