/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invariant Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getInvariantRule()
 * @model
 * @generated
 */
public interface InvariantRule extends SpecDeclRule
{
} // InvariantRule
