/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lhs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.Lhs#getTarget <em>Target</em>}</li>
 *   <li>{@link uclid.xtext.uclid.Lhs#getIndex <em>Index</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getLhs()
 * @model
 * @generated
 */
public interface Lhs extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(VarRef)
   * @see uclid.xtext.uclid.UclidPackage#getLhs_Target()
   * @model containment="true"
   * @generated
   */
  VarRef getTarget();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.Lhs#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(VarRef value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.ExprRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getLhs_Index()
   * @model containment="true"
   * @generated
   */
  EList<ExprRule> getIndex();

} // Lhs
