/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getOutputDecl()
 * @model
 * @generated
 */
public interface OutputDecl extends TypedObjectDecl
{
} // OutputDecl
