/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getPropertyRule()
 * @model
 * @generated
 */
public interface PropertyRule extends SpecDeclRule
{
} // PropertyRule
