/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Record Type Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.RecordTypeRule#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getRecordTypeRule()
 * @model
 * @generated
 */
public interface RecordTypeRule extends Type
{
  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.IdTypeListRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getRecordTypeRule_Fields()
   * @model containment="true"
   * @generated
   */
  EList<IdTypeListRule> getFields();

} // RecordTypeRule
