/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shared Vars Decl Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uclid.xtext.uclid.UclidPackage#getSharedVarsDeclRule()
 * @model
 * @generated
 */
public interface SharedVarsDeclRule extends DeclRule
{
} // SharedVarsDeclRule
