/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Synonym Type Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.SynonymTypeRule#getDecl <em>Decl</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getSynonymTypeRule()
 * @model
 * @generated
 */
public interface SynonymTypeRule extends Type
{
  /**
   * Returns the value of the '<em><b>Decl</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl</em>' reference.
   * @see #setDecl(TypeDecl)
   * @see uclid.xtext.uclid.UclidPackage#getSynonymTypeRule_Decl()
   * @model
   * @generated
   */
  TypeDecl getDecl();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.SynonymTypeRule#getDecl <em>Decl</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decl</em>' reference.
   * @see #getDecl()
   * @generated
   */
  void setDecl(TypeDecl value);

} // SynonymTypeRule
