/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.Type#getT <em>T</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' attribute.
   * @see #setT(String)
   * @see uclid.xtext.uclid.UclidPackage#getType_T()
   * @model
   * @generated
   */
  String getT();

  /**
   * Sets the value of the '{@link uclid.xtext.uclid.Type#getT <em>T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' attribute.
   * @see #getT()
   * @generated
   */
  void setT(String value);

} // Type
