/**
 * generated by Xtext 2.24.0
 */
package uclid.xtext.uclid;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uclid.xtext.uclid.VarReference#getIndex <em>Index</em>}</li>
 * </ul>
 *
 * @see uclid.xtext.uclid.UclidPackage#getVarReference()
 * @model
 * @generated
 */
public interface VarReference extends E13Rule
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference list.
   * The list contents are of type {@link uclid.xtext.uclid.ExprRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference list.
   * @see uclid.xtext.uclid.UclidPackage#getVarReference_Index()
   * @model containment="true"
   * @generated
   */
  EList<ExprRule> getIndex();

} // VarReference
