/**
 * generated by Xtext 2.22.0
 */
package uclid.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uclid.xtext.UclidRuntimeModule;
import uclid.xtext.UclidStandaloneSetup;
import uclid.xtext.ide.UclidIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UclidIdeSetup extends UclidStandaloneSetup {
  @Override
  public Injector createInjector() {
    UclidRuntimeModule _uclidRuntimeModule = new UclidRuntimeModule();
    UclidIdeModule _uclidIdeModule = new UclidIdeModule();
    return Guice.createInjector(Modules2.mixin(_uclidRuntimeModule, _uclidIdeModule));
  }
}
