/*
 * generated by Xtext 2.24.0
 */
package uclid.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUclidScopeProvider extends DelegatingScopeProvider {
}
