/*
 * generated by Xtext 2.22.0
 */
package uclid.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uclid.xtext.ide.contentassist.antlr.internal.InternalUclidParser;
import uclid.xtext.services.UclidGrammarAccess;

public class UclidParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UclidGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UclidGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDeclRuleAccess().getAlternatives(), "rule__DeclRule__Alternatives");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getAlternatives(), "rule__TypeDeclRule__Alternatives");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getAlternatives_0_1(), "rule__TypeDeclRule__Alternatives_0_1");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getAlternatives(), "rule__AxiomDeclRule__Alternatives");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getAlternatives_0_0(), "rule__AxiomDeclRule__Alternatives_0_0");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getAlternatives_1_0(), "rule__AxiomDeclRule__Alternatives_1_0");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getAlternatives(), "rule__SpecDeclRule__Alternatives");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getPropAlternatives_0_0_0(), "rule__SpecDeclRule__PropAlternatives_0_0_0");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getPropAlternatives_1_0_0(), "rule__SpecDeclRule__PropAlternatives_1_0_0");
			builder.put(grammarAccess.getStatementRuleAccess().getAlternatives(), "rule__StatementRule__Alternatives");
			builder.put(grammarAccess.getCallStatementAccess().getAlternatives(), "rule__CallStatement__Alternatives");
			builder.put(grammarAccess.getCaseStmtRuleAccess().getCasesAlternatives_2_0(), "rule__CaseStmtRule__CasesAlternatives_2_0");
			builder.put(grammarAccess.getInvariantClauseRuleAccess().getAlternatives_0(), "rule__InvariantClauseRule__Alternatives_0");
			builder.put(grammarAccess.getE1RuleAccess().getAlternatives(), "rule__E1Rule__Alternatives");
			builder.put(grammarAccess.getE1RuleAccess().getPredAlternatives_1_1_0(), "rule__E1Rule__PredAlternatives_1_1_0");
			builder.put(grammarAccess.getE2RuleAccess().getQAlternatives_1_1_0(), "rule__E2Rule__QAlternatives_1_1_0");
			builder.put(grammarAccess.getE3RuleAccess().getEAlternatives_1_1_0(), "rule__E3Rule__EAlternatives_1_1_0");
			builder.put(grammarAccess.getE4RuleAccess().getAlternatives(), "rule__E4Rule__Alternatives");
			builder.put(grammarAccess.getE10RuleAccess().getAlternatives(), "rule__E10Rule__Alternatives");
			builder.put(grammarAccess.getE10RuleAccess().getOpAlternatives_0_0_0(), "rule__E10Rule__OpAlternatives_0_0_0");
			builder.put(grammarAccess.getE11RuleAccess().getAlternatives(), "rule__E11Rule__Alternatives");
			builder.put(grammarAccess.getE11RuleAccess().getAlternatives_0_3(), "rule__E11Rule__Alternatives_0_3");
			builder.put(grammarAccess.getE13RuleAccess().getAlternatives(), "rule__E13Rule__Alternatives");
			builder.put(grammarAccess.getConstRuleAccess().getAlternatives(), "rule__ConstRule__Alternatives");
			builder.put(grammarAccess.getTypeRuleAccess().getAlternatives(), "rule__TypeRule__Alternatives");
			builder.put(grammarAccess.getPrimitiveTypeRuleAccess().getTAlternatives_0(), "rule__PrimitiveTypeRule__TAlternatives_0");
			builder.put(grammarAccess.getCmdNameRuleAccess().getAlternatives(), "rule__CmdNameRule__Alternatives");
			builder.put(grammarAccess.getIdListRuleAccess().getAlternatives(), "rule__IdListRule__Alternatives");
			builder.put(grammarAccess.getModelRuleAccess().getGroup(), "rule__ModelRule__Group__0");
			builder.put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
			builder.put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
			builder.put(grammarAccess.getModuleRuleAccess().getGroup(), "rule__ModuleRule__Group__0");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getGroup_0(), "rule__TypeDeclRule__Group_0__0");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getGroup_1(), "rule__TypeDeclRule__Group_1__0");
			builder.put(grammarAccess.getInputsDeclRuleAccess().getGroup(), "rule__InputsDeclRule__Group__0");
			builder.put(grammarAccess.getOutputsDeclRuleAccess().getGroup(), "rule__OutputsDeclRule__Group__0");
			builder.put(grammarAccess.getVarsDeclRuleAccess().getGroup(), "rule__VarsDeclRule__Group__0");
			builder.put(grammarAccess.getVarsDeclRuleAccess().getGroup_1(), "rule__VarsDeclRule__Group_1__0");
			builder.put(grammarAccess.getVarsDeclRuleAccess().getGroup_1_1(), "rule__VarsDeclRule__Group_1_1__0");
			builder.put(grammarAccess.getConstsDeclRuleAccess().getGroup(), "rule__ConstsDeclRule__Group__0");
			builder.put(grammarAccess.getConstsDeclRuleAccess().getGroup_2(), "rule__ConstsDeclRule__Group_2__0");
			builder.put(grammarAccess.getConstsDeclRuleAccess().getGroup_5(), "rule__ConstsDeclRule__Group_5__0");
			builder.put(grammarAccess.getConstDeclAccess().getGroup(), "rule__ConstDecl__Group__0");
			builder.put(grammarAccess.getSharedVarsDeclRuleAccess().getGroup(), "rule__SharedVarsDeclRule__Group__0");
			builder.put(grammarAccess.getDefineDeclRuleAccess().getGroup(), "rule__DefineDeclRule__Group__0");
			builder.put(grammarAccess.getFunctionDeclAccess().getGroup(), "rule__FunctionDecl__Group__0");
			builder.put(grammarAccess.getProcedureDeclAccess().getGroup(), "rule__ProcedureDecl__Group__0");
			builder.put(grammarAccess.getProcReturnArgRuleAccess().getGroup(), "rule__ProcReturnArgRule__Group__0");
			builder.put(grammarAccess.getRequireExprsRuleAccess().getGroup(), "rule__RequireExprsRule__Group__0");
			builder.put(grammarAccess.getEnsureExprsRuleAccess().getGroup(), "rule__EnsureExprsRule__Group__0");
			builder.put(grammarAccess.getModifiesExprsRuleAccess().getGroup(), "rule__ModifiesExprsRule__Group__0");
			builder.put(grammarAccess.getInstanceDeclRuleAccess().getGroup(), "rule__InstanceDeclRule__Group__0");
			builder.put(grammarAccess.getArgMapListRuleAccess().getGroup(), "rule__ArgMapListRule__Group__0");
			builder.put(grammarAccess.getArgMapListRuleAccess().getGroup_2(), "rule__ArgMapListRule__Group_2__0");
			builder.put(grammarAccess.getArgMapListRuleAccess().getGroup_2_1(), "rule__ArgMapListRule__Group_2_1__0");
			builder.put(grammarAccess.getArgMapRuleAccess().getGroup(), "rule__ArgMapRule__Group__0");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getGroup_0(), "rule__AxiomDeclRule__Group_0__0");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getGroup_1(), "rule__AxiomDeclRule__Group_1__0");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getGroup_0(), "rule__SpecDeclRule__Group_0__0");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getGroup_1(), "rule__SpecDeclRule__Group_1__0");
			builder.put(grammarAccess.getInitDeclRuleAccess().getGroup(), "rule__InitDeclRule__Group__0");
			builder.put(grammarAccess.getNextDeclRuleAccess().getGroup(), "rule__NextDeclRule__Group__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_0(), "rule__StatementRule__Group_0__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_1(), "rule__StatementRule__Group_1__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_2(), "rule__StatementRule__Group_2__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_3(), "rule__StatementRule__Group_3__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_4(), "rule__StatementRule__Group_4__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_5(), "rule__StatementRule__Group_5__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_6(), "rule__StatementRule__Group_6__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_7(), "rule__StatementRule__Group_7__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_8(), "rule__StatementRule__Group_8__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_9(), "rule__StatementRule__Group_9__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_10(), "rule__StatementRule__Group_10__0");
			builder.put(grammarAccess.getStatementRuleAccess().getGroup_11(), "rule__StatementRule__Group_11__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_0(), "rule__CallStatement__Group_0__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_0_1(), "rule__CallStatement__Group_0_1__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_0_1_2(), "rule__CallStatement__Group_0_1_2__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_0_1_2_1(), "rule__CallStatement__Group_0_1_2_1__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_0_1_8(), "rule__CallStatement__Group_0_1_8__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_1(), "rule__CallStatement__Group_1__0");
			builder.put(grammarAccess.getCallStatementAccess().getGroup_1_4(), "rule__CallStatement__Group_1_4__0");
			builder.put(grammarAccess.getAssignmentRuleAccess().getGroup(), "rule__AssignmentRule__Group__0");
			builder.put(grammarAccess.getAssignmentRuleAccess().getGroup_1(), "rule__AssignmentRule__Group_1__0");
			builder.put(grammarAccess.getAssignmentRuleAccess().getGroup_1_1(), "rule__AssignmentRule__Group_1_1__0");
			builder.put(grammarAccess.getAssignmentRuleAccess().getGroup_4(), "rule__AssignmentRule__Group_4__0");
			builder.put(grammarAccess.getBlkStmtRuleAccess().getGroup(), "rule__BlkStmtRule__Group__0");
			builder.put(grammarAccess.getLhsAccess().getGroup(), "rule__Lhs__Group__0");
			builder.put(grammarAccess.getLhsAccess().getGroup_2(), "rule__Lhs__Group_2__0");
			builder.put(grammarAccess.getLhsAccess().getGroup_2_2(), "rule__Lhs__Group_2_2__0");
			builder.put(grammarAccess.getIfStmtRuleAccess().getGroup(), "rule__IfStmtRule__Group__0");
			builder.put(grammarAccess.getIfStmtRuleAccess().getGroup_5(), "rule__IfStmtRule__Group_5__0");
			builder.put(grammarAccess.getCaseStmtRuleAccess().getGroup(), "rule__CaseStmtRule__Group__0");
			builder.put(grammarAccess.getDefaultCaseBlockRuleAccess().getGroup(), "rule__DefaultCaseBlockRule__Group__0");
			builder.put(grammarAccess.getCaseBlockRuleAccess().getGroup(), "rule__CaseBlockRule__Group__0");
			builder.put(grammarAccess.getForLoopRuleAccess().getGroup(), "rule__ForLoopRule__Group__0");
			builder.put(grammarAccess.getWhileLoopRuleAccess().getGroup(), "rule__WhileLoopRule__Group__0");
			builder.put(grammarAccess.getInvariantClauseRuleAccess().getGroup(), "rule__InvariantClauseRule__Group__0");
			builder.put(grammarAccess.getInvariantClauseRuleAccess().getGroup_1(), "rule__InvariantClauseRule__Group_1__0");
			builder.put(grammarAccess.getE1RuleAccess().getGroup_1(), "rule__E1Rule__Group_1__0");
			builder.put(grammarAccess.getE2RuleAccess().getGroup(), "rule__E2Rule__Group__0");
			builder.put(grammarAccess.getE2RuleAccess().getGroup_1(), "rule__E2Rule__Group_1__0");
			builder.put(grammarAccess.getE3RuleAccess().getGroup(), "rule__E3Rule__Group__0");
			builder.put(grammarAccess.getE3RuleAccess().getGroup_1(), "rule__E3Rule__Group_1__0");
			builder.put(grammarAccess.getE4RuleAccess().getGroup_0(), "rule__E4Rule__Group_0__0");
			builder.put(grammarAccess.getE4RuleAccess().getGroup_1(), "rule__E4Rule__Group_1__0");
			builder.put(grammarAccess.getE4RuleAccess().getGroup_2(), "rule__E4Rule__Group_2__0");
			builder.put(grammarAccess.getE4RuleAccess().getGroup_3(), "rule__E4Rule__Group_3__0");
			builder.put(grammarAccess.getE4RuleAccess().getGroup_4(), "rule__E4Rule__Group_4__0");
			builder.put(grammarAccess.getE5RuleAccess().getGroup(), "rule__E5Rule__Group__0");
			builder.put(grammarAccess.getE5RuleAccess().getGroup_1(), "rule__E5Rule__Group_1__0");
			builder.put(grammarAccess.getE6RuleAccess().getGroup(), "rule__E6Rule__Group__0");
			builder.put(grammarAccess.getE6RuleAccess().getGroup_1(), "rule__E6Rule__Group_1__0");
			builder.put(grammarAccess.getE7RuleAccess().getGroup(), "rule__E7Rule__Group__0");
			builder.put(grammarAccess.getE7RuleAccess().getGroup_1(), "rule__E7Rule__Group_1__0");
			builder.put(grammarAccess.getE8RuleAccess().getGroup(), "rule__E8Rule__Group__0");
			builder.put(grammarAccess.getE8RuleAccess().getGroup_1(), "rule__E8Rule__Group_1__0");
			builder.put(grammarAccess.getE9RuleAccess().getGroup(), "rule__E9Rule__Group__0");
			builder.put(grammarAccess.getE9RuleAccess().getGroup_1(), "rule__E9Rule__Group_1__0");
			builder.put(grammarAccess.getE10RuleAccess().getGroup_0(), "rule__E10Rule__Group_0__0");
			builder.put(grammarAccess.getE11RuleAccess().getGroup_0(), "rule__E11Rule__Group_0__0");
			builder.put(grammarAccess.getE11RuleAccess().getGroup_0_3_0(), "rule__E11Rule__Group_0_3_0__0");
			builder.put(grammarAccess.getE11RuleAccess().getGroup_0_3_1(), "rule__E11Rule__Group_0_3_1__0");
			builder.put(grammarAccess.getE12RuleAccess().getGroup(), "rule__E12Rule__Group__0");
			builder.put(grammarAccess.getE12RuleAccess().getGroup_1(), "rule__E12Rule__Group_1__0");
			builder.put(grammarAccess.getRHSVarRefAccess().getGroup(), "rule__RHSVarRef__Group__0");
			builder.put(grammarAccess.getRHSVarRefAccess().getGroup_1(), "rule__RHSVarRef__Group_1__0");
			builder.put(grammarAccess.getTupleExprAccess().getGroup(), "rule__TupleExpr__Group__0");
			builder.put(grammarAccess.getTupleExprAccess().getGroup_2(), "rule__TupleExpr__Group_2__0");
			builder.put(grammarAccess.getIfPrimaryExprAccess().getGroup(), "rule__IfPrimaryExpr__Group__0");
			builder.put(grammarAccess.getParenthesisExprAccess().getGroup(), "rule__ParenthesisExpr__Group__0");
			builder.put(grammarAccess.getConstRuleAccess().getGroup_2(), "rule__ConstRule__Group_2__0");
			builder.put(grammarAccess.getEnumTypeRuleAccess().getGroup(), "rule__EnumTypeRule__Group__0");
			builder.put(grammarAccess.getEnumTypeRuleAccess().getGroup_4(), "rule__EnumTypeRule__Group_4__0");
			builder.put(grammarAccess.getEnumValueAccess().getGroup(), "rule__EnumValue__Group__0");
			builder.put(grammarAccess.getTupleTypeRuleAccess().getGroup(), "rule__TupleTypeRule__Group__0");
			builder.put(grammarAccess.getTupleTypeRuleAccess().getGroup_3(), "rule__TupleTypeRule__Group_3__0");
			builder.put(grammarAccess.getRecordTypeRuleAccess().getGroup(), "rule__RecordTypeRule__Group__0");
			builder.put(grammarAccess.getArrayTypeRuleAccess().getGroup(), "rule__ArrayTypeRule__Group__0");
			builder.put(grammarAccess.getArrayTypeRuleAccess().getGroup_3(), "rule__ArrayTypeRule__Group_3__0");
			builder.put(grammarAccess.getSynonymTypeRuleAccess().getGroup(), "rule__SynonymTypeRule__Group__0");
			builder.put(grammarAccess.getControlBlockRuleAccess().getGroup(), "rule__ControlBlockRule__Group__0");
			builder.put(grammarAccess.getCmdRuleAccess().getGroup(), "rule__CmdRule__Group__0");
			builder.put(grammarAccess.getCmdRuleAccess().getGroup_0(), "rule__CmdRule__Group_0__0");
			builder.put(grammarAccess.getCmdRuleAccess().getGroup_1(), "rule__CmdRule__Group_1__0");
			builder.put(grammarAccess.getCmdRuleAccess().getGroup_3(), "rule__CmdRule__Group_3__0");
			builder.put(grammarAccess.getCmdRuleAccess().getGroup_4(), "rule__CmdRule__Group_4__0");
			builder.put(grammarAccess.getIdListRuleAccess().getGroup_1(), "rule__IdListRule__Group_1__0");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getGroup(), "rule__IdTypeListRule__Group__0");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getGroup_1(), "rule__IdTypeListRule__Group_1__0");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getGroup_4(), "rule__IdTypeListRule__Group_4__0");
			builder.put(grammarAccess.getExprListRuleAccess().getGroup(), "rule__ExprListRule__Group__0");
			builder.put(grammarAccess.getExprListRuleAccess().getGroup_2(), "rule__ExprListRule__Group_2__0");
			builder.put(grammarAccess.getModelRuleAccess().getRulesAssignment_1(), "rule__ModelRule__RulesAssignment_1");
			builder.put(grammarAccess.getModuleRuleAccess().getNameAssignment_2(), "rule__ModuleRule__NameAssignment_2");
			builder.put(grammarAccess.getModuleRuleAccess().getDAssignment_4(), "rule__ModuleRule__DAssignment_4");
			builder.put(grammarAccess.getModuleRuleAccess().getEAssignment_5(), "rule__ModuleRule__EAssignment_5");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getNameAssignment_0_1_0(), "rule__TypeDeclRule__NameAssignment_0_1_0");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getTAssignment_0_3(), "rule__TypeDeclRule__TAssignment_0_3");
			builder.put(grammarAccess.getTypeDeclRuleAccess().getNameAssignment_1_1(), "rule__TypeDeclRule__NameAssignment_1_1");
			builder.put(grammarAccess.getInputsDeclRuleAccess().getTAssignment_3(), "rule__InputsDeclRule__TAssignment_3");
			builder.put(grammarAccess.getOutputsDeclRuleAccess().getTAssignment_3(), "rule__OutputsDeclRule__TAssignment_3");
			builder.put(grammarAccess.getVarsDeclRuleAccess().getVarsAssignment_1_0(), "rule__VarsDeclRule__VarsAssignment_1_0");
			builder.put(grammarAccess.getVarsDeclRuleAccess().getVarsAssignment_1_1_1(), "rule__VarsDeclRule__VarsAssignment_1_1_1");
			builder.put(grammarAccess.getVarsDeclRuleAccess().getTAssignment_3(), "rule__VarsDeclRule__TAssignment_3");
			builder.put(grammarAccess.getVarDeclAccess().getNameAssignment(), "rule__VarDecl__NameAssignment");
			builder.put(grammarAccess.getConstsDeclRuleAccess().getConstantsAssignment_1(), "rule__ConstsDeclRule__ConstantsAssignment_1");
			builder.put(grammarAccess.getConstsDeclRuleAccess().getConstantsAssignment_2_1(), "rule__ConstsDeclRule__ConstantsAssignment_2_1");
			builder.put(grammarAccess.getConstsDeclRuleAccess().getTAssignment_4(), "rule__ConstsDeclRule__TAssignment_4");
			builder.put(grammarAccess.getConstDeclAccess().getNameAssignment_1(), "rule__ConstDecl__NameAssignment_1");
			builder.put(grammarAccess.getSharedVarsDeclRuleAccess().getTAssignment_3(), "rule__SharedVarsDeclRule__TAssignment_3");
			builder.put(grammarAccess.getDefineDeclRuleAccess().getNameAssignment_1(), "rule__DefineDeclRule__NameAssignment_1");
			builder.put(grammarAccess.getDefineDeclRuleAccess().getLAssignment_3(), "rule__DefineDeclRule__LAssignment_3");
			builder.put(grammarAccess.getDefineDeclRuleAccess().getTAssignment_6(), "rule__DefineDeclRule__TAssignment_6");
			builder.put(grammarAccess.getDefineDeclRuleAccess().getEAssignment_8(), "rule__DefineDeclRule__EAssignment_8");
			builder.put(grammarAccess.getFunctionDeclAccess().getNameAssignment_2(), "rule__FunctionDecl__NameAssignment_2");
			builder.put(grammarAccess.getFunctionDeclAccess().getLAssignment_4(), "rule__FunctionDecl__LAssignment_4");
			builder.put(grammarAccess.getFunctionDeclAccess().getTAssignment_7(), "rule__FunctionDecl__TAssignment_7");
			builder.put(grammarAccess.getProcedureDeclAccess().getNameAssignment_2(), "rule__ProcedureDecl__NameAssignment_2");
			builder.put(grammarAccess.getProcedureDeclAccess().getLAssignment_4(), "rule__ProcedureDecl__LAssignment_4");
			builder.put(grammarAccess.getProcedureDeclAccess().getRetAssignment_6(), "rule__ProcedureDecl__RetAssignment_6");
			builder.put(grammarAccess.getProcedureDeclAccess().getReqAssignment_7(), "rule__ProcedureDecl__ReqAssignment_7");
			builder.put(grammarAccess.getProcedureDeclAccess().getEnsureAssignment_8(), "rule__ProcedureDecl__EnsureAssignment_8");
			builder.put(grammarAccess.getProcedureDeclAccess().getModifiesAssignment_9(), "rule__ProcedureDecl__ModifiesAssignment_9");
			builder.put(grammarAccess.getProcedureDeclAccess().getBodyAssignment_10(), "rule__ProcedureDecl__BodyAssignment_10");
			builder.put(grammarAccess.getProcReturnArgRuleAccess().getLAssignment_2(), "rule__ProcReturnArgRule__LAssignment_2");
			builder.put(grammarAccess.getRequireExprsRuleAccess().getEAssignment_1(), "rule__RequireExprsRule__EAssignment_1");
			builder.put(grammarAccess.getEnsureExprsRuleAccess().getEAssignment_1(), "rule__EnsureExprsRule__EAssignment_1");
			builder.put(grammarAccess.getModifiesExprsRuleAccess().getLAssignment_1(), "rule__ModifiesExprsRule__LAssignment_1");
			builder.put(grammarAccess.getInstanceDeclRuleAccess().getNameAssignment_1(), "rule__InstanceDeclRule__NameAssignment_1");
			builder.put(grammarAccess.getInstanceDeclRuleAccess().getModuleAssignment_3(), "rule__InstanceDeclRule__ModuleAssignment_3");
			builder.put(grammarAccess.getInstanceDeclRuleAccess().getArgsAssignment_4(), "rule__InstanceDeclRule__ArgsAssignment_4");
			builder.put(grammarAccess.getArgMapListRuleAccess().getArgAssignment_2_0(), "rule__ArgMapListRule__ArgAssignment_2_0");
			builder.put(grammarAccess.getArgMapListRuleAccess().getArgAssignment_2_1_1(), "rule__ArgMapListRule__ArgAssignment_2_1_1");
			builder.put(grammarAccess.getArgMapRuleAccess().getNameAssignment_1(), "rule__ArgMapRule__NameAssignment_1");
			builder.put(grammarAccess.getArgMapRuleAccess().getEAssignment_4(), "rule__ArgMapRule__EAssignment_4");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getNAssignment_0_1(), "rule__AxiomDeclRule__NAssignment_0_1");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getEAssignment_0_3(), "rule__AxiomDeclRule__EAssignment_0_3");
			builder.put(grammarAccess.getAxiomDeclRuleAccess().getHAssignment_1_1(), "rule__AxiomDeclRule__HAssignment_1_1");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getPropAssignment_0_0(), "rule__SpecDeclRule__PropAssignment_0_0");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getNameAssignment_0_1(), "rule__SpecDeclRule__NameAssignment_0_1");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getEAssignment_0_3(), "rule__SpecDeclRule__EAssignment_0_3");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getPropAssignment_1_0(), "rule__SpecDeclRule__PropAssignment_1_0");
			builder.put(grammarAccess.getSpecDeclRuleAccess().getEAssignment_1_1(), "rule__SpecDeclRule__EAssignment_1_1");
			builder.put(grammarAccess.getInitDeclRuleAccess().getBodyAssignment_1(), "rule__InitDeclRule__BodyAssignment_1");
			builder.put(grammarAccess.getNextDeclRuleAccess().getBodyAssignment_1(), "rule__NextDeclRule__BodyAssignment_1");
			builder.put(grammarAccess.getStatementRuleAccess().getDAssignment_1_1(), "rule__StatementRule__DAssignment_1_1");
			builder.put(grammarAccess.getStatementRuleAccess().getDAssignment_2_1(), "rule__StatementRule__DAssignment_2_1");
			builder.put(grammarAccess.getStatementRuleAccess().getNameAssignment_3_1(), "rule__StatementRule__NameAssignment_3_1");
			builder.put(grammarAccess.getStatementRuleAccess().getNameAssignment_6_2(), "rule__StatementRule__NameAssignment_6_2");
			builder.put(grammarAccess.getStatementRuleAccess().getSAssignment_7_0(), "rule__StatementRule__SAssignment_7_0");
			builder.put(grammarAccess.getStatementRuleAccess().getSAssignment_8_0(), "rule__StatementRule__SAssignment_8_0");
			builder.put(grammarAccess.getStatementRuleAccess().getSAssignment_9_0(), "rule__StatementRule__SAssignment_9_0");
			builder.put(grammarAccess.getStatementRuleAccess().getSAssignment_10_0(), "rule__StatementRule__SAssignment_10_0");
			builder.put(grammarAccess.getStatementRuleAccess().getSAssignment_11_0(), "rule__StatementRule__SAssignment_11_0");
			builder.put(grammarAccess.getCallStatementAccess().getLhsAssignment_0_1_2_0(), "rule__CallStatement__LhsAssignment_0_1_2_0");
			builder.put(grammarAccess.getCallStatementAccess().getLhsAssignment_0_1_2_1_1(), "rule__CallStatement__LhsAssignment_0_1_2_1_1");
			builder.put(grammarAccess.getCallStatementAccess().getTargetAssignment_0_1_5(), "rule__CallStatement__TargetAssignment_0_1_5");
			builder.put(grammarAccess.getCallStatementAccess().getExprsAssignment_0_1_7(), "rule__CallStatement__ExprsAssignment_0_1_7");
			builder.put(grammarAccess.getCallStatementAccess().getExprsAssignment_0_1_8_1(), "rule__CallStatement__ExprsAssignment_0_1_8_1");
			builder.put(grammarAccess.getCallStatementAccess().getTargetAssignment_1_1(), "rule__CallStatement__TargetAssignment_1_1");
			builder.put(grammarAccess.getCallStatementAccess().getExprsAssignment_1_3(), "rule__CallStatement__ExprsAssignment_1_3");
			builder.put(grammarAccess.getCallStatementAccess().getExprsAssignment_1_4_1(), "rule__CallStatement__ExprsAssignment_1_4_1");
			builder.put(grammarAccess.getAssignmentRuleAccess().getLhsAssignment_1_0(), "rule__AssignmentRule__LhsAssignment_1_0");
			builder.put(grammarAccess.getAssignmentRuleAccess().getLhsAssignment_1_1_1(), "rule__AssignmentRule__LhsAssignment_1_1_1");
			builder.put(grammarAccess.getAssignmentRuleAccess().getExprsAssignment_3(), "rule__AssignmentRule__ExprsAssignment_3");
			builder.put(grammarAccess.getAssignmentRuleAccess().getExprsAssignment_4_1(), "rule__AssignmentRule__ExprsAssignment_4_1");
			builder.put(grammarAccess.getBlkStmtRuleAccess().getDecAssignment_2(), "rule__BlkStmtRule__DecAssignment_2");
			builder.put(grammarAccess.getBlkStmtRuleAccess().getStmtAssignment_3(), "rule__BlkStmtRule__StmtAssignment_3");
			builder.put(grammarAccess.getLhsAccess().getTargetAssignment_1(), "rule__Lhs__TargetAssignment_1");
			builder.put(grammarAccess.getLhsAccess().getIndexAssignment_2_1(), "rule__Lhs__IndexAssignment_2_1");
			builder.put(grammarAccess.getLhsAccess().getIndexAssignment_2_2_1(), "rule__Lhs__IndexAssignment_2_2_1");
			builder.put(grammarAccess.getLhsVarRefAccess().getVarAssignment(), "rule__LhsVarRef__VarAssignment");
			builder.put(grammarAccess.getIfStmtRuleAccess().getCAssignment_2(), "rule__IfStmtRule__CAssignment_2");
			builder.put(grammarAccess.getIfStmtRuleAccess().getThenAssignment_4(), "rule__IfStmtRule__ThenAssignment_4");
			builder.put(grammarAccess.getIfStmtRuleAccess().getElseAssignment_5_1(), "rule__IfStmtRule__ElseAssignment_5_1");
			builder.put(grammarAccess.getCaseStmtRuleAccess().getCasesAssignment_2(), "rule__CaseStmtRule__CasesAssignment_2");
			builder.put(grammarAccess.getDefaultCaseBlockRuleAccess().getBodyAssignment_2(), "rule__DefaultCaseBlockRule__BodyAssignment_2");
			builder.put(grammarAccess.getCaseBlockRuleAccess().getEAssignment_0(), "rule__CaseBlockRule__EAssignment_0");
			builder.put(grammarAccess.getCaseBlockRuleAccess().getBodyAssignment_2(), "rule__CaseBlockRule__BodyAssignment_2");
			builder.put(grammarAccess.getForLoopRuleAccess().getIteratorAssignment_1(), "rule__ForLoopRule__IteratorAssignment_1");
			builder.put(grammarAccess.getForLoopRuleAccess().getLbAssignment_5(), "rule__ForLoopRule__LbAssignment_5");
			builder.put(grammarAccess.getForLoopRuleAccess().getUbAssignment_7(), "rule__ForLoopRule__UbAssignment_7");
			builder.put(grammarAccess.getForLoopRuleAccess().getBodyAssignment_9(), "rule__ForLoopRule__BodyAssignment_9");
			builder.put(grammarAccess.getWhileLoopRuleAccess().getCAssignment_2(), "rule__WhileLoopRule__CAssignment_2");
			builder.put(grammarAccess.getWhileLoopRuleAccess().getInvAssignment_4(), "rule__WhileLoopRule__InvAssignment_4");
			builder.put(grammarAccess.getWhileLoopRuleAccess().getStmtAssignment_5(), "rule__WhileLoopRule__StmtAssignment_5");
			builder.put(grammarAccess.getInvariantClauseRuleAccess().getEAssignment_2(), "rule__InvariantClauseRule__EAssignment_2");
			builder.put(grammarAccess.getE1RuleAccess().getPredAssignment_1_1(), "rule__E1Rule__PredAssignment_1_1");
			builder.put(grammarAccess.getE1RuleAccess().getLAssignment_1_3(), "rule__E1Rule__LAssignment_1_3");
			builder.put(grammarAccess.getE1RuleAccess().getAAssignment_1_6(), "rule__E1Rule__AAssignment_1_6");
			builder.put(grammarAccess.getE2RuleAccess().getZAssignment_0(), "rule__E2Rule__ZAssignment_0");
			builder.put(grammarAccess.getE2RuleAccess().getQAssignment_1_1(), "rule__E2Rule__QAssignment_1_1");
			builder.put(grammarAccess.getE3RuleAccess().getEAssignment_0(), "rule__E3Rule__EAssignment_0");
			builder.put(grammarAccess.getE3RuleAccess().getEAssignment_1_1(), "rule__E3Rule__EAssignment_1_1");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_0_0(), "rule__E4Rule__EAssignment_0_0");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_0_2(), "rule__E4Rule__EAssignment_0_2");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_1_0(), "rule__E4Rule__EAssignment_1_0");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_1_2(), "rule__E4Rule__EAssignment_1_2");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_2_0(), "rule__E4Rule__EAssignment_2_0");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_2_2(), "rule__E4Rule__EAssignment_2_2");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_3_0(), "rule__E4Rule__EAssignment_3_0");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_3_2(), "rule__E4Rule__EAssignment_3_2");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_4_0(), "rule__E4Rule__EAssignment_4_0");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_4_2(), "rule__E4Rule__EAssignment_4_2");
			builder.put(grammarAccess.getE4RuleAccess().getEAssignment_5(), "rule__E4Rule__EAssignment_5");
			builder.put(grammarAccess.getE5RuleAccess().getEAssignment_0(), "rule__E5Rule__EAssignment_0");
			builder.put(grammarAccess.getE5RuleAccess().getOpAssignment_1_0(), "rule__E5Rule__OpAssignment_1_0");
			builder.put(grammarAccess.getE5RuleAccess().getEAssignment_1_1(), "rule__E5Rule__EAssignment_1_1");
			builder.put(grammarAccess.getE6RuleAccess().getEAssignment_0(), "rule__E6Rule__EAssignment_0");
			builder.put(grammarAccess.getE6RuleAccess().getEAssignment_1_1(), "rule__E6Rule__EAssignment_1_1");
			builder.put(grammarAccess.getE7RuleAccess().getEAssignment_0(), "rule__E7Rule__EAssignment_0");
			builder.put(grammarAccess.getE7RuleAccess().getEAssignment_1_1(), "rule__E7Rule__EAssignment_1_1");
			builder.put(grammarAccess.getE8RuleAccess().getEAssignment_0(), "rule__E8Rule__EAssignment_0");
			builder.put(grammarAccess.getE8RuleAccess().getEAssignment_1_1(), "rule__E8Rule__EAssignment_1_1");
			builder.put(grammarAccess.getE9RuleAccess().getEAssignment_0(), "rule__E9Rule__EAssignment_0");
			builder.put(grammarAccess.getE9RuleAccess().getEAssignment_1_1(), "rule__E9Rule__EAssignment_1_1");
			builder.put(grammarAccess.getE10RuleAccess().getOpAssignment_0_0(), "rule__E10Rule__OpAssignment_0_0");
			builder.put(grammarAccess.getE10RuleAccess().getEAssignment_0_1(), "rule__E10Rule__EAssignment_0_1");
			builder.put(grammarAccess.getE10RuleAccess().getEAssignment_1(), "rule__E10Rule__EAssignment_1");
			builder.put(grammarAccess.getE11RuleAccess().getLAssignment_0_2(), "rule__E11Rule__LAssignment_0_2");
			builder.put(grammarAccess.getE11RuleAccess().getEAssignment_0_3_0_1(), "rule__E11Rule__EAssignment_0_3_0_1");
			builder.put(grammarAccess.getE11RuleAccess().getEAssignment_0_3_1_1(), "rule__E11Rule__EAssignment_0_3_1_1");
			builder.put(grammarAccess.getE12RuleAccess().getJAssignment_0(), "rule__E12Rule__JAssignment_0");
			builder.put(grammarAccess.getE12RuleAccess().getVAssignment_1_1(), "rule__E12Rule__VAssignment_1_1");
			builder.put(grammarAccess.getRHSVarRefAccess().getVarAssignment_1_0(), "rule__RHSVarRef__VarAssignment_1_0");
			builder.put(grammarAccess.getRHSVarRefAccess().getPrimeAssignment_1_1(), "rule__RHSVarRef__PrimeAssignment_1_1");
			builder.put(grammarAccess.getEnumRefAccess().get_enumAssignment(), "rule__EnumRef___enumAssignment");
			builder.put(grammarAccess.getTupleExprAccess().getEAssignment_1(), "rule__TupleExpr__EAssignment_1");
			builder.put(grammarAccess.getTupleExprAccess().getEAssignment_2_1(), "rule__TupleExpr__EAssignment_2_1");
			builder.put(grammarAccess.getIfPrimaryExprAccess().getCAssignment_2(), "rule__IfPrimaryExpr__CAssignment_2");
			builder.put(grammarAccess.getIfPrimaryExprAccess().getEAssignment_5(), "rule__IfPrimaryExpr__EAssignment_5");
			builder.put(grammarAccess.getIfPrimaryExprAccess().getEAssignment_7(), "rule__IfPrimaryExpr__EAssignment_7");
			builder.put(grammarAccess.getConstRuleAccess().getVAssignment_0(), "rule__ConstRule__VAssignment_0");
			builder.put(grammarAccess.getConstRuleAccess().getVAssignment_1(), "rule__ConstRule__VAssignment_1");
			builder.put(grammarAccess.getConstRuleAccess().getDAssignment_2_0(), "rule__ConstRule__DAssignment_2_0");
			builder.put(grammarAccess.getConstRuleAccess().getWAssignment_2_1(), "rule__ConstRule__WAssignment_2_1");
			builder.put(grammarAccess.getConstRuleAccess().getVAssignment_3(), "rule__ConstRule__VAssignment_3");
			builder.put(grammarAccess.getPrimitiveTypeRuleAccess().getTAssignment(), "rule__PrimitiveTypeRule__TAssignment");
			builder.put(grammarAccess.getEnumTypeRuleAccess().getEnumsAssignment_3(), "rule__EnumTypeRule__EnumsAssignment_3");
			builder.put(grammarAccess.getEnumTypeRuleAccess().getEnumsAssignment_4_1(), "rule__EnumTypeRule__EnumsAssignment_4_1");
			builder.put(grammarAccess.getEnumValueAccess().getNameAssignment_1(), "rule__EnumValue__NameAssignment_1");
			builder.put(grammarAccess.getTupleTypeRuleAccess().getTupleAssignment_2(), "rule__TupleTypeRule__TupleAssignment_2");
			builder.put(grammarAccess.getTupleTypeRuleAccess().getTupleAssignment_3_1(), "rule__TupleTypeRule__TupleAssignment_3_1");
			builder.put(grammarAccess.getRecordTypeRuleAccess().getFieldsAssignment_3(), "rule__RecordTypeRule__FieldsAssignment_3");
			builder.put(grammarAccess.getArrayTypeRuleAccess().getBAssignment_2(), "rule__ArrayTypeRule__BAssignment_2");
			builder.put(grammarAccess.getArrayTypeRuleAccess().getBAssignment_3_1(), "rule__ArrayTypeRule__BAssignment_3_1");
			builder.put(grammarAccess.getArrayTypeRuleAccess().getBaseAssignment_5(), "rule__ArrayTypeRule__BaseAssignment_5");
			builder.put(grammarAccess.getSynonymTypeRuleAccess().getDeclAssignment_1(), "rule__SynonymTypeRule__DeclAssignment_1");
			builder.put(grammarAccess.getControlBlockRuleAccess().getCmdAssignment_3(), "rule__ControlBlockRule__CmdAssignment_3");
			builder.put(grammarAccess.getCmdRuleAccess().getLhsAssignment_0_0(), "rule__CmdRule__LhsAssignment_0_0");
			builder.put(grammarAccess.getCmdRuleAccess().getCAssignment_2(), "rule__CmdRule__CAssignment_2");
			builder.put(grammarAccess.getCmdRuleAccess().getLidAssignment_3_1(), "rule__CmdRule__LidAssignment_3_1");
			builder.put(grammarAccess.getCmdRuleAccess().getLexAssignment_4_1(), "rule__CmdRule__LexAssignment_4_1");
			builder.put(grammarAccess.getIdListRuleAccess().getNameAssignment_0(), "rule__IdListRule__NameAssignment_0");
			builder.put(grammarAccess.getIdListRuleAccess().getNameAssignment_1_0(), "rule__IdListRule__NameAssignment_1_0");
			builder.put(grammarAccess.getIdListRuleAccess().getLAssignment_1_2(), "rule__IdListRule__LAssignment_1_2");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getKAssignment_0(), "rule__IdTypeListRule__KAssignment_0");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getZAssignment_1_1(), "rule__IdTypeListRule__ZAssignment_1_1");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getTAssignment_3(), "rule__IdTypeListRule__TAssignment_3");
			builder.put(grammarAccess.getIdTypeListRuleAccess().getLAssignment_4_1(), "rule__IdTypeListRule__LAssignment_4_1");
			builder.put(grammarAccess.getExprListRuleAccess().getExprsAssignment_1(), "rule__ExprListRule__ExprsAssignment_1");
			builder.put(grammarAccess.getExprListRuleAccess().getExprsAssignment_2_1(), "rule__ExprListRule__ExprsAssignment_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UclidGrammarAccess grammarAccess;

	@Override
	protected InternalUclidParser createParser() {
		InternalUclidParser result = new InternalUclidParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UclidGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UclidGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
